name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the call
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List iles
        run: ls
      - name: Output Information
        run: echo "Deploying & Uploading..."
